apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ol2g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ol2g
    app.kubernetes.io/part-of: tkrw-pr712-0075-0065-app
  name: devfile-sample-ol2g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ol2g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ol2g
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-ol2g@sha256:0a50ae5ba2a3432b245803b83f05b114316c48908049f7f03fb18540f8942174
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
