apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ol2g
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-ol2g@sha256:0a50ae5ba2a3432b245803b83f05b114316c48908049f7f03fb18540f8942174
        name: my-nodejs
        resources: {}
status: {}
